((deffacts iniciales (a)(c)(d)(e)(g)(h)(k)

)
(defrule r1 (k)(l)(m)=>(assert(i)))
(defrule r2 (i)(l)(j)=>(assert(q)))
(defrule r3 (c)(d)(e)=>(assert(b)))
(defrule r4 (a)(b)=>(assert(q)))
(defrule r5 (l)(n)(o)(p)=>(assert(q)))
(defrule r6 (c)(h)=>(assert(r)))
(defrule r7 (r)(j)(m)=>(assert(s)))
(defrule r8 (t)(f)(h)=>(assert(b)))
(defrule r9 (a)=>(assert(f)))
(defrule r10 (a)(r)=>(assert(t)))
(defrule r11 (c)(a)(r)=>(assert(v))))